### ISSUE TITLE
Remove trailing slash when making a request.

### ISSUE THREAD

**Issue by abdulaziz-jm** [tailflow/laravel-orion-ts#8] opened 2021-06-14 02:53 UTC
First of all, thank you for making this library, I love working with it.

Issue description:
When making a request with trailing slash `api/somemodel/`, the web server respond with `301 Moved Permanently` this will result in losing the data when you make a post request.

I'm using Laravel 8 and apache.

The only other way to solve this that I know of is changing your .htaccess.

See these issues:
https://github.com/laravel/framework/discussions/32955
https://github.com/laravel/framework/issues/23
https://stackoverflow.com/questions/18934588/json-giving-301-moved-permanently
https://stackoverflow.com/questions/48805861/laravel-301-moved-permanently-from-disk-cache

**Comment by alexzarbn** [comment] 2021-06-22 04:03
Hi @abdulaziz-jm,

Thank you for raising this issue! I will look into implementing the fix somewhere this week.

**Comment by b166er** [comment] 2021-08-19 20:41
laravel ignores trailing slashes in routes or is not sensitive to trailing slashes. Both URLs look the same for the route. Can the developer please decide what to do with the URL and not laravel.

Route::get('/test', function () {return "No Trailing Slash";});
Route::get('/test/', function () {return "Trailing Slash";}); // <-- will be active because it is the last line

thanks.

**Comment by alexzarbn** [comment] 2021-08-21 04:20
Hi @abdulaziz-jm,

Sorry for the late overdue. The issue is fixed in [v2.1.1](https://github.com/tailflow/laravel-orion-ts/releases/tag/2.1.1) release.

**Closed by alexzarbn** 2021-08-21 04:20 UTC
Labels: bug
